# Generated by Django 4.0.5 on 2022-07-03 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Наименование модели')),
                ('description', models.TextField(verbose_name='Описание')),
                ('children', models.CharField(max_length=50, verbose_name='Список потомков')),
            ],
        ),
        migrations.CreateModel(
            name='RelationModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameFrom', models.CharField(max_length=50, verbose_name='Наименование родителя')),
                ('nameTo', models.CharField(max_length=50, verbose_name='Наименование потомка')),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.model')),
            ],
        ),
    ]
