# Generated by Django 4.0.5 on 2022-07-03 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_model_children'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationmodel',
            name='model',
        ),
        migrations.DeleteModel(
            name='Model',
        ),
        migrations.DeleteModel(
            name='RelationModel',
        ),
    ]
